# -*- encoding: utf-8 -*-
"""
locksmith.core.indirecting module

Mailbox director and supporting classes

"""
import datetime
import sys
import traceback

from hio.base import doing
from hio.help import decking
from keri import help, kering
from keri.app import httping, agenting
from keri.app.habbing import GroupHab
from keri.core import (parsing, routing)
from keri.db import basing
from keri.help import helping
from ordered_set import OrderedSet as oset

logger = help.ogler.getLogger()


class MailboxDirector(doing.DoDoer):
    """
    Coordinates the management, routing, and processing of mailboxes and related systems.

    The `MailboxDirector` class integrates various components to handle incoming
    messages, manage subscriptions, and coordinate with verifiers and exchangers. It implements
    a directed workflow for processing messages, handling replies, and managing escrows. Its
    design supports extensive configuration, making it adaptable to different mailbox-related
    use cases.

    Attributes:
        hby: Hierarchical key store manager for managing key-related operations.
        exchanger: Instance for facilitating and managing exchanges between participants.
        rep: Manages replies, including state or record tracking.
        topics: List of topic identifiers for subscriptions or notifications.
        pollers: List of poller instances for handling polling mechanisms.
        cues: Queue or deck for processing cues generated during message handling.
        ims: Default parser buffer. Mailbox frames are passed to the parser separately.
        messages: Queue of complete messages received from mailbox pollers.
        rgy: Native registry manager owned by the vault.
        rtr: Router responsible for message routing to appropriate handlers or verifiers.
        rvy: Verifies routes for received messages and processes message verifications.
        kvy: Used for key events and registering reply routes.
        parser: Parses incoming data streams and delegates processing to relevant components.
    """

    def __init__(self, hby, topics, rgy, kvy, exc, ims=None,
                 rep=None, cues=None, rvy=None, **kwa):
        """
        Initializes the MailboxDirector class, which is responsible for managing mailboxes,
        routing messages, handling replies, and processing incoming data streams. It ensures
        coordination between different components like verifiers, exchangers, routers, and
        processors.

        Parameters:
            hby: Object responsible for managing the local hierarchical key store.
            topics: Topic identifiers for subscription or notification handling.
            ims: Optional default parser buffer. Mailbox frames use separate buffers.
            kvy: Required key event verifier with a Kramer for pending key evidence.
            exc: Required exchanger for message verification and pending exchanges.
            rep: Optional object for managing reply records or states.
            cues: Optional queue or deck for processing cues generated by the component.
            rvy: Optional router/verifier object for managing received routes.
            rgy: Native registry manager owned by the vault.
            **kwa: Additional keyword arguments passed to the parent class initializer.
        """
        self.hby = hby
        self.rgy = rgy
        self.exchanger = exc
        self.rep = rep
        self.topics = topics
        self.pollers = list()
        self.prefixes = oset()
        self.cues = cues if cues is not None else decking.Deck()

        self.ims = ims if ims is not None else bytearray()
        self.messages = decking.Deck()

        doers = []
        doers.extend([doing.doify(self.pollDo),
                      doing.doify(self.msgDo),
                      doing.doify(self.escrowDo)])

        self.rtr = routing.Router()
        self.rvy = rvy

        self.kvy = kvy
        self.kvy.registerReplyRoutes(self.rtr)

        self.parser = parsing.Parser(ims=self.ims,
                                     framed=True,
                                     kvy=self.kvy,
                                     exc=self.exchanger,
                                     rvy=self.rvy,
                                     version=kering.Vrsn_2_0)

        super(MailboxDirector, self).__init__(doers=doers, **kwa)

    @property
    def mailboxes(self):
        return oset([(poller.hab.name, poller.hab.pre, poller.mailbox) for poller in self.pollers])

    def wind(self, tymth):
        """
        Bind this director and its child doers to the scheduler clock.

        Args:
            tymth: Callable that returns the scheduler time in seconds.
        """
        super(MailboxDirector, self).wind(tymth)

    def pollDo(self, tymth=None, tock=0.0, **kwa):
        """ Queue complete messages from remote mailbox pollers
         
        Parameters:
            tymth: injected function wrapper closure returned by .tymen() of
                Tymist instance. Calling tymth() returns the associated Tymist .tyme.
            tock (float): injected initial tock value in seconds
            **kwa: additional keyword arguments
         
         """
        # enter context
        self.wind(tymth)
        self.tock = tock
        _ = (yield self.tock)

        while True:
            for msg in self.processPollIter():
                self.messages.append(msg)
                _ = (yield self.tock)
            _ = (yield self.tock)

    def add_poller(self, hab, mailbox):
        """
        Adds a new Poller instance to the current object and extends its structure with the new Poller.

        This method creates a Poller object using the provided `hab` and `mailbox` parameters. The newly
        created Poller is added to the `pollers` list and also extends the current object's iterable
        structure.

        Parameters:
            hab: The habitat or context required to configure the Poller instance.
            mailbox: The witness or source used by the Poller instance for polling activities.
        """

        poller = Poller(hab=hab, topics=self.topics, mailbox=mailbox)
        self.pollers.append(poller)
        self.extend([poller])

    def processPollIter(self):
        """
        Drain the messages queued by each mailbox poller.

        Yields:
            One complete mailbox message at a time.

        """
        mail = []
        for poller in self.pollers:  # get responses from all behaviors
            while poller.msgs:
                msg = poller.msgs.popleft()
                mail.append(msg)

        while mail:  # iteratively process each response in responses
            msg = mail.pop(0)
            yield msg

    def msgDo(self, tymth=None, tock=0.0, **kwa):
        """
        Parse queued mailbox messages.

        Select the attachment version for each frame before validation.

        Scheduler:
            Wrap this generator with doing.doify to schedule it as a doer.
            Yield the delay before the next scheduler step.

        Parameters:
            tymth is injected function wrapper closure returned by .tymen() of
                Tymist instance. Calling tymth() returns the associated Tymist .tyme.
            tock is injected initial tock value

        Usage:
            Add doing.doify(self.msgDo) to the doers list.
        """
        self.wind(tymth)
        self.tock = tock
        _ = (yield self.tock)

        while True:
            while self.messages:
                msg = bytearray(self.messages.popleft())
                version = kering.Vrsn_2_0
                try:
                    v1_body = (kering.sniff(msg) == kering.Colds.msg
                               and kering.smell(msg).pvrsn == kering.Vrsn_1_0)
                except kering.KeriError:
                    v1_body = False  # Let the parser discard the malformed frame.
                if v1_body:
                    # V1 bodies do not identify their attachment genus. Extract
                    # the whole frame without validation before choosing V1.
                    try:
                        yield from self.parser.groupParsator(
                            ims=bytearray(msg), framed=True, local=False,
                            version=kering.Vrsn_2_0, processive=False)
                    except Exception:
                        version = kering.Vrsn_1_0
                self.parser.parse(ims=msg, version=version, local=False)
                yield self.tock
            yield self.tock

    def escrowDo(self, tymth=None, tock=0.0, **kwa):
        """
        Retry pending key, reply, exchange, and registry evidence.

        Scheduler:
            Wrap this generator with doing.doify to schedule it as a doer.
            Yield the delay before the next scheduler step.

        Parameters:
            tymth is injected function wrapper closure returned by .tymen() of
                Tymist instance. Calling tymth() returns the associated Tymist .tyme.
            tock is injected initial tock value

        Usage:
            Add doing.doify(self.escrowDo) to the doers list.
        """
        self.wind(tymth)
        self.tock = tock
        _ = (yield self.tock)

        while True:
            self.kvy.processEscrows()
            if self.rvy:
                self.rvy.processEscrowReply()
            self.exchanger.processEscrow()
            self.rgy.processEscrows()
            # No receiver evidence fetcher consumes these transient cues yet.
            self.kvy.kramer.cues.clear()
            self.exchanger.cues.clear()

            yield

    @property
    def times(self):
        times = dict()
        for poller in self.pollers:  # get responses from all pollers
            times |= poller.times

        return times

    def remove_poller(self, hab, mailbox):
        """
        Remove a Poller instance from the director.

        Finds the poller matching the hab and mailbox, removes it from the pollers list,
        and properly closes it via the DoDoer remove mechanism.

        Parameters:
            hab: The habitat associated with the poller to remove.
            mailbox: The mailbox EID associated with the poller to remove.
        """
        # Find the poller to remove
        poller_to_remove = None
        for poller in self.pollers:
            if poller.hab.pre == hab.pre and poller.mailbox == mailbox:
                poller_to_remove = poller
                break

        if poller_to_remove is not None:
            self.pollers.remove(poller_to_remove)
            self.remove([poller_to_remove])  # This closes the poller via DoDoer.remove()
            logger.info(f"Removed poller for hab={hab.pre}, mailbox={mailbox}")
        else:
            logger.warning(f"No poller found for hab={hab.pre}, mailbox={mailbox}")


class Poller(doing.DoDoer):
    """
    Polls remote SSE endpoint for event that are KERI messages to be processed

    """

    def __init__(self, hab, mailbox, topics, msgs=None, retry=1000, **kwa):
        """
        Initializes an instance of the Poller class.

        Args:
            hab: The habitat instance associated with the poller.
            mailbox: The identifier or locator of the witness to be polled.
            topics: The topics or channels to monitor or poll for events.
            msgs: Optional; a deque or collection of messages to process. Defaults to None.
            retry: Optional; the retry interval in milliseconds. Defaults to 1000.
            **kwa: Additional keyword arguments for customization.
        """
        self.hab = hab
        self.pre = hab.pre
        self.mailbox = mailbox
        self.topics = topics
        self.retry = retry
        self.msgs = None if msgs is not None else decking.Deck()
        self.times = dict()

        doers = [doing.doify(self.eventDo)]

        super(Poller, self).__init__(doers=doers, **kwa)

    def eventDo(self, tymth=None, tock=0.0, **kwa):
        """
        Handles event-driven processing and communication with a witness through HTTP, retrying operations
        based on a given number of attempts and managing message queries and responses.

        Args:
            tymth: A generator function reference for timing control, which facilitates coroutine scheduling or
                task management within the event loop. Defaults to None.
            tock: A float representing the duration of the time slice (in seconds) for processing in the event loop.
                Defaults to 0.0.
            **kwa: Arbitrary keyword arguments that may be provided to the underlying functionality, allowing
                flexibility in extending the method's behavior or integrating with external components.

        Yields:
            float: The duration of sleep intervals or processing delays during various operations, which may vary
                based on the execution context and retry logic.

        """
        self.wind(tymth)
        self.tock = tock
        _ = (yield self.tock)

        witrec = self.hab.db.tops.get((self.pre, self.mailbox))
        if witrec is None:
            witrec = basing.TopicsRecord(topics=dict())

        while self.retry > 0:
            try:
                client, clientDoer = agenting.httpClient(self.hab, self.mailbox)
            except kering.MissingEntryError as e:
                traceback.print_exception(e, file=sys.stderr)  # logging
                yield self.tock
                continue

            self.extend([clientDoer])

            topics = dict()
            q = dict(pre=self.pre, topics=topics)
            for topic in self.topics:
                if topic in witrec.topics:
                    topics[topic] = witrec.topics[topic] + 1
                else:
                    topics[topic] = 0

            # Create query message
            if isinstance(self.hab, GroupHab):
                msg = self.hab.mhab.query(
                    pre=self.pre,
                    src=self.mailbox,
                    route="mbx",
                    query=q,
                    version=kering.Vrsn_2_0,
                    gvrsn=kering.Vrsn_2_0,
                    kind=kering.Kinds.json,
                )  # type: ignore
            else:
                msg = self.hab.query(
                    pre=self.pre,
                    src=self.mailbox,
                    route="mbx",
                    query=q,
                    version=kering.Vrsn_2_0,
                    gvrsn=kering.Vrsn_2_0,
                    kind=kering.Kinds.json,
                )

            httping.createCESRRequest(msg, client, dest=self.mailbox)

            while client.requests:
                yield self.tock

            created = helping.nowUTC()
            while True:

                now = helping.nowUTC()
                if now - created > datetime.timedelta(seconds=30):
                    self.remove([clientDoer])
                    break

                while client.events:
                    evt = client.events.popleft()
                    if "retry" in evt:
                        self.retry = evt["retry"]
                    if "id" not in evt or "data" not in evt or "name" not in evt:
                        logger.error(f"bad mailbox event: {evt}")
                        continue
                    idx = evt["id"]
                    msg = evt["data"]
                    tpc = evt["name"]

                    if not idx or not msg or not tpc:
                        logger.error(f"bad mailbox event: {evt}")
                        continue

                    self.msgs.append(msg.encode("utf=8"))
                    yield self.tock

                    witrec.topics[tpc] = int(idx)
                    self.times[tpc] = helping.nowUTC()
                    self.hab.db.tops.pin((self.pre, self.mailbox), witrec)

                yield 0.25
            yield self.retry / 1000
